### ISSUE TITLE
Port for Waveshare 1.14inch LCD v2 (ST7789VW LCD)

### ISSUE THREAD

**Issue by OldMate6288** [j-selby/oxidgb-pico#2]
Hey, just wanted to start by saying I love your project! Got it setup on my PicoDisplay and it looks so cool.

I was wondering if you're still working on this, would you be willing to port the code to work on the Waveshare 1.14inch LCD v2 with button support? I feel like this LCD's button mapping would work perfectly with your emulator.

I would do it myself but I absolutely suck at Rust and have a lot to learn, I'm more than happy to donate some money for your time if you're willing to help out.

Thanks!

**Comment by j-selby** [comment]
Hi! Looking at https://github.com/j-selby/oxidgb-pico/issues/1, it looks like there could be good potential here for a generic interface for displays which would make this a lot easier for people to port around.

Your display shouldn't be too difficult to implement - https://docs.rs/st7789/0.3.0/st7789/struct.ST7789.html has the driver already ready for use in Rust. I'll put some thought into how to do this properly!

**Comment by OldMate6288** [comment]
Absolute legend, thank you so much for looking into this I really appreciate it!

**Comment by j-selby** [comment]
I've updated the package to use rp-pico and the ST7789 driver itself (same as what I have mostly - ST7789 vs ST7789VW) - hopefully it should just work for your screen now! You can modify https://github.com/j-selby/oxidgb-pico/blob/c349cedaffb14ba88eebbfcf2a7a4c59faad0f04/src/main.rs#L139-L164 depending on what pins you are using.

**Comment by OldMate6288** [comment]
I really appreciate this! I'm currently trying to build the release folder but when compiling st7789 it pops up with an error saying: linker 'flip-link' not found, note: no such file or directory.

I went to the link for the lcd but couldn't find the file, unsure what I need to do from here to fix it.

**Comment by j-selby** [comment]
Whoops, sorry - forgot that I added those. I've updated the documentation to fix that one. The commands you are looking for are:
```
cargo install flip-link
cargo install probe-run
```

**Comment by OldMate6288** [comment]
I'm legit so sorry to bother you again but I still can't get it to work on my lcd. I got it to compile with those commands you sent me and it works with no issues on the pico display still, but even after changing the pinouts I still just get a blank lcd. I tried looking at waveshares example codes to see if I could figure out the issue but had no luck. Here's the code I edited if it helps:

let _spi_sclk = pins.gpio10.into_mode::<hal::gpio::FunctionSpi>();
        let _spi_mosi = pins.gpio11.into_mode::<hal::gpio::FunctionSpi>();
        // We're using what would normally be the miso pin for data/command
        let dc = pins.gpio8.into_push_pull_output();
        // Chip select
        let cs = pins.gpio9.into_push_pull_output();
        // Backlight
        let bl = pins.gpio13.into_push_pull_output();

        // Setup and init the SPI device
        let spi = bsp::hal::Spi::<_, _, 8>::new(pac.SPI0);

        let spi = spi.init(
            &mut pac.RESETS,
            clocks.peripheral_clock.freq(),
            //16_000_000u32.Hz(),
            32_000_000u32.Hz(),
            &embedded_hal::spi::MODE_3,
        );

        // Set properties of the screen we are using
        let properties = DisplayProperties {
            display_width: 240,
            display_height: 135,
            x_offset: 40,
            y_offset: 53,
        };

        // Add input handling
        let button_a = pins.gpio15.into_pull_up_input();
        let button_b = pins.gpio17.into_pull_up_input();
        let button_up = pins.gpio2.into_pull_up_input();
        let button_down = pins.gpio18.into_pull_up_input();
        let button_left = pins.gpio16.into_pull_up_input();
        let button_right = pins.gpio20.into_pull_up_input();
        let button_ctrl = pins.gpio3.into_pull_up_input();

        let input_handler = move || {
            let mut input: heapless::Vec<GameboyButton, 4> = heapless::Vec::new();

            if button_a.is_low().unwrap() {
                input.push(GameboyButton::A).unwrap();
            }
            if button_b.is_low().unwrap() {
                input.push(GameboyButton::B).unwrap();
            }
            if button_up.is_low().unwrap() {
                input.push(GameboyButton::UP).unwrap();
            }
            if button_down.is_low().unwrap() {
                input.push(GameboyButton::DOWN).unwrap();
            }
            if button_left.is_low().unwrap() {
                input.push(GameboyButton::LEFT).unwrap();
            }
            if button_right.is_low().unwrap() {
                input.push(GameboyButton::RIGHT).unwrap();
            }
            if button_ctrl.is_low().unwrap() {
                input.push(GameboyButton::START).unwrap();
            }

            build_input(&input)
        };

        (

and the pinout reference I followed: https://www.waveshare.com/wiki/Pico-LCD-1.14

**Comment by j-selby** [comment]
Hmmm - that's unlucky. Not sure there is too much I can do, but maybe playing around with the reset pin might work?

https://github.com/j-selby/oxidgb-pico/blob/master/src/main.rs#L480 - maybe change that to `Some(pins.gpio12.into_push_pull_output())`? 
Other than that, its worth playing around which which pins are which, changing `embedded_hal::spi::MODE_3` to something else (MODE_0, MODE_1, MODE_2).

Sorry I can't be more help!

**Comment by j-selby** [comment]
(Reset pin might actually be what is causing it if it is left floating, so definitely give above a go)
